### ISSUE TITLE
Cannot run ti on Ubuntu 10.10

### ISSUE THREAD

**Issue by alecthegeek** [schacon/ticgit#12]
I'm running Ubuntu 10.10 (Maverick). I followed the install instructions for Debian (twice) but seem to be missing something. The error message when I run ti

/var/lib/gems/1.8/gems/TicGit-ng-1.0.2.2/lib/ticgit-ng/cli.rb:235:in `puts': private method`puts' called for nil:NilClass (NoMethodError)

(PS I'm a Ruby and Gems n00b, so please forgive any obvious steps)

**Comment by jeffWelling** [comment]
Hey! Thanks for asking for help instead of just giving up on the project :)
I haven't tried installing ticgit on Ubuntu in awhile, once I get home from work I will throw together a ubuntu virtual machine and try to reproduce this bug. I may as well write ubunti-specific instructions while I'm at it too hehe. Should be the same though.
I don't recall there being any specific obvious tricks, it looks like you found a genuine bug :)
Check back tomorrow and hopefully it will be fixed, with new ubuntu specific instructions to boot. Thanks for filing the bug.
Jeff.

**Comment by alecthegeek** [comment]
FYI: I'm running 64bit

**Comment by jeffWelling** [comment]
Thanks, that part _is_ important. :)

**Comment by jeffWelling** [comment]
I've tried reproducing the error you described in Ubuntu 10.10 64Bit in a virtual machine, but haven't been successful. Can you provide more information about exactly what steps you performed?

Line 235 in cli.rb is  doing
    @out.puts(...)
And `@out` defaults to `$stdout`.. so I have to ask just for posterity, have you made changes to the code that your running, and or, are you providing an additional options to the `ti` command line?

Any information you can give me that helps me reproduce and thus fix the problem will help and is appreciated :)

**Comment by alecthegeek** [comment]
I will try on a clean VM here over the next couple of days. I'm guessing it's some cruft on my laptop system. Do I have to set any environment variables to let Ruby find libraries?

**Comment by jeffWelling** [comment]
By default, I'm not aware of any requirements like that.  There's always the possibility of something like rvm or multiple ruby installs complicating things... 

Could you try making a change to the code and running it? 
If not, I could make said change here in a branch, and package it as a gem and email it to you. Then you could install that gem and send me the debug output.
We need to find out why `@out`, or perhaps `$stdout` is nil...

**Comment by alecthegeek** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I installed Ubuntu 10.10 64bit VM plus updates and then followed the
installtion of packages detailed in the readme. I also added
`/var/lib/gems/1.8/bin` to my path

I got exactly the same error

I've looked at the line that throws the exception `@out.puts(*strings)`
and I've no idea how to add appropriate debugging :-(. Hints welcome

---

Alec Clews
Personal alec.clews@gmail.com                  Melbourne, Australia
Jabber:  alecclews@jabber.org                   PGPKey ID: 0x9BBBFC7C
Blog  http://alecthegeek.wordpress.com/
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk2gZUwACgkQP+e5j5u7/HxbRACfXvfrPMJtgyhslbcefBObP4an
cZkAnj0sp8mb85ZXV4peWYC46L10QojR
=o+5O
-----END PGP SIGNATURE-----

**Comment by jeffWelling** [comment]
Hmm. lol Most intriguing.
I'm retrying with a fresh install.
So, the only commands that you do after the fresh install to get this to happen are;
    $ sudo apt-get install git-core ruby rubygems
    $ sudo gem install git TicGit-ng
    $ ....
Actually, you know what... what `ti` command are you running? 
Are you doing just simply `ti` ?  Or are you trying a command like `ti new`?

VM is reinstalling now...

**Comment by alecthegeek** [comment]
Here is the edited version of my shell log file

sudo apt-get install git ruby rubygems
sudo gem install git
sudo apt-get install git ruby rubygems
sudo gem install git sinatra haml sass
sudo apt-get -t testing install git-core
sudo gem install TicGit-ng
PATH=$PATH:/var/lib/gems/1.8/bin
ti help

**Comment by jeffWelling** [comment]
BLAST!

I'd written a nice extensive detailed reply, and then restarted my computer due to a Spotlight fuckup, and lost all that work.  Sigh.  Oh well.

So, long story short, in pursuing this bug I've found one other, and I believe I may have solved this problem.
I think the problem is that you are calling `ti` without being in a git repository.

Can you try this for me?
`mkdir temp`  
`cd temp`  
`git clone git@github.com:jeffWelling/ticgit.git`  
`cd ticgit`  
`ti`  

And see if you get the same error?
Once you've tested that, you can just delete the `temp` directory.

TicGit expects, or rather erroneously assumes, that before being called the user knows to `cd` into a git repository.  This assumption needs to be corrected and I've filed a bug for it in the issue tracker under my TicGit fork.

Thanks for bringing this to my attention :)
Does this solve the bug your seeing? If so, can you comment and close the ticket, and if not post another comment and we'll keep banging away at it.
Cheers,
Jeff Welling

**Comment by jeffWelling** [comment]
Oh, for reference, this is that other bug that I found.
https://github.com/jeffWelling/ticgit/issues/#issue/18

**Comment by alecthegeek** [comment]
Fixed as per last message above.

Thanks
